baseurl = "http://justinmccandless.com/"
languageCode = "en-us"
title = "Justin McCandless"
author = "Justin McCandless"

[params]
  logo      = "/images/logo.png"
  description = "Computer science, engineering, travel"
  copyright = "Justin McCandless. All rights reserved."
  twitter   = "https://twitter.com/justinjmcc"
  twitter_name   = "justinjmcc"
  github    = "https://github.com/justinmc"
  email     = "justinjmccandless@gmail.com"
  google_analytics = "UA-32798612-1"
  disqusShortname = "justinmccandless"
